# Generated by Django 3.1.2 on 2020-11-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish')),
            ],
        ),
    ]
