# Generated by Django 3.1.2 on 2020-11-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='dishess',
            new_name='dishes',
        ),
    ]
