# Generated by Django 3.1.2 on 2020-11-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201111_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='dishes',
        ),
    ]
