# Generated by Django 3.1.2 on 2020-11-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_basket_dishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_to_basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
