# Generated by Django 3.1.2 on 2020-11-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20201111_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish_to_basket',
            new_name='Dish_in_basket',
        ),
    ]
