# Generated by Django 3.1.2 on 2020-11-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20201111_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='portion_for',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
