# Generated by Django 2.2.12 on 2020-11-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20201116_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='short_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
