# Generated by Django 3.1.2 on 2020-11-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20201124_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name_plural': 'Basket'},
        ),
    ]
