# Generated by Django 3.1.2 on 2020-11-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20201124_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_in_basket',
            name='basket_pk',
            field=models.IntegerField(default=0),
        ),
    ]
