# Generated by Django 3.1.2 on 2020-11-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20201125_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='similar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.dish'),
        ),
    ]
