# Generated by Django 3.1.2 on 2020-11-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_dish_similar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='similar',
        ),
        migrations.AddField(
            model_name='dish',
            name='similar',
            field=models.ManyToManyField(blank=True, null=True, related_name='_dish_similar_+', to='menu.Dish'),
        ),
    ]
